# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6d5f0dbeb5cd1ca387d127b69886658d8fd3c88a8ee4e31338bb818e1a7365e3579252f26feba956772f4d0affcd16f4843ba910c33316094fd98b4d603b012

test:
  secret_key_base: 4a58c06f78823f999eadf3fbdfaaabab9901071e9fd91fccb649733147b3885071cce45823c84a0f8d2a485517f952618e9352fe5e12d925ca9bd2177277f280

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
